# from https://zenn.dev/kawarimidoll/articles/c68204d248c107#設定ファイル
name: update-deno-dependencies

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  udd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.18.2
      - name: Update dependencies
        run: >
          deno run --allow-net --allow-read=deps.ts --allow-write=deps.ts
          --allow-run=deno https://deno.land/x/udd@0.7.2/main.ts deps.ts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: ":arrow_up: update deno dependencies"
          title: Update Deno Dependencies
          body: >
            Automated updates by [deno-udd](https://github.com/hayd/deno-udd)
            and [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action
          branch: update-deno-dependencies
          author: GitHub <noreply@github.com>
          delete-branch: true
